# Generated by Django 3.2.4 on 2021-06-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
